version: '3.8'

services:
  coolify-mcp-debug:
    build:
      context: .
      dockerfile: tmp/Dockerfile.debug
    container_name: coolify-mcp-debug
    environment:
      # Load from .env file
      COOLIFY_BASE_URL: "${COOLIFY_BASE_URL}"
      COOLIFY_ACCESS_TOKEN: "${COOLIFY_ACCESS_TOKEN}"
      DEBUG: "coolify:*"
      NODE_ENV: "development"
    # Interactive mode for debugging
    stdin_open: true
    tty: true
    # Mount source for live debugging
    volumes:
      - ./tmp:/app/tmp
      - ./logs:/app/logs
    restart: "no"  # Don't restart automatically for debugging

  # Production-like test
  coolify-mcp-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coolify-mcp-test
    environment:
      COOLIFY_BASE_URL: "${COOLIFY_BASE_URL}"
      COOLIFY_ACCESS_TOKEN: "${COOLIFY_ACCESS_TOKEN}"
      DEBUG: "coolify:*"
      NODE_ENV: "production"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
