services:
  coolify-mcp:
    image: image: ghcr.io/carsaig/coolify-mcp:latest
    container_name: coolify-mcp
    environment:
      COOLIFY_BASE_URL: "op://Private/Coolify/BASE_URL"
      COOLIFY_ACCESS_TOKEN: "op://Private/Coolify/API_Token"
    expose:
      - "3000"
        networks:
      - mcp-net

  networks:
  mcp-net:
    external: true
